# SITE CONFIGURATION
baseurl:
#"test_blog"
url: ""

# THEME-SPECIFIC CONFIGURATION
title: NC State RC-SIT                                    # site's title
description: "NC State Research Computing Solutions and InTegration  "      # used by search engines
avatar: assets/img/mainlogo.png                         # Empty for no avatar in navbar
favicon: assets/background-color.ico
#favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: <code>NC State RC-SIT</code>  # Change Blog header text
#header_feature_image: assets/img/pexels/triangular.jpeg
header_feature_image: assets/img/background-color.png
avatar1: assets/img/ncsu_oit-logo.png 

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  faq:
    output: true
  workshop: 
    output: true
  projects:
    output: true
  tutorials:
    output: true
  downloads:
    output: true
  howto:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*", ".travis.yml",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

