#! /usr/bin/bash
echo "     "
echo "clear all"
echo "clear matrix"
echo "clear mata"
echo  "        "
echo "set more off"
echo "        "
echo "/* Unlike in Windows, where memory is */"
echo "/*managed automatically, you should set */"
echo "/*maximum memory when running Stata in Linux */"
echo "       "
echo "set max_memory 16g, permanent "
echo "              "
echo "/* create a MyRegDir in home directory to */"
echo "/* store regression output                   */"
echo "/* mkdir \$HOME/MyRegDir */"  
echo "/*mkdir $HOME/MyRegDir */"
echo "/* cd $HOME/MyRegDir */"
echo "                 "
echo "set obs 10000"
echo "gen y = rnormal(3,1)"
echo "gen x1 = rnormal(1,1)"
echo "gen x2 = runiform(0,1)"
echo "gen x3 = rnormal(0,1)"
echo  "              "
echo "/* store sample data in sample.dta */"
echo "/* save /share/$GROUP/$USER/sample.dta, replace */"
echo "          "
echo "save /share/$GROUP/$USER/sample.dta, replace"
echo "use /share/$GROUP/$USER/sample.dta, clear"
echo "            "
echo "/* install ivreg2, as ssc install ivreg2 when you run */"
echo "/* install, ranktest from within Stata as ssc inst ranktest */"
echo "/* install, outreg2 from within Stata as ssc inst outreg2 */"
echo "/* Stata interactively at your home directory */"
echo "                "
echo "ivreg2 y x3 (x1 = x2)" 
echo "             "
echo "/* Output regression results iv_est.xml */"
echo "outreg2 using iv_est, excel long stat(coef tstat) paren(tstat) e(r2_a rmse) ctitle(y, iv: x2) "



